DATE=$(date "+%Y/%m/%d")
TABLE_NAME="pluto_input_cama_dof"

# create temporary location
mkdir -p tmp && cd tmp && { 
    # curl to directory
    curl -O $FTP_PREFIX/agencySourceData/dof/pluto_input_cama_dof.txt;
    
    # # add colum nme
    sed -i 1i"BBL|PARCELCARD|BLDGNUM|BLDGCLASS|PRIMARYUSECODE|DEVELOPMENTNAME|STREETTYPE|LOTTYPE|RESIDAREA|OFFICEAREA|RETAILAREA|GARAGEAREA|STORAGEAREA|FACTORYAREA|OTHERAREA|GROSSAREA|OWNERAREA|GROSSVOLUME|COMMERCIALAREA|PROXCODE|BSMNT_TYPE|BSMNTGRADIENT|BSMNTAREA|FIRSTFLOORAREA|SECONDFLOORAREA|UPPERFLOORAREA|PARTRESFLOORAREA|UNFINISHEDFLOORAREA|FINISHEDFLOORAREA|NONRESIDFLOORAREA|RESIDCONSTRTYPE|COMMERCIALCONSTRTYPE|CONDOMAINCONSTRTYPE|CONDOUNITSCONSTRTYPE" $TABLE_NAME.txt
    
    # # Check number of rows
    wc -l $TABLE_NAME.txt

    # # Check number of columns
    awk -F'|' '{print NF; exit}' $TABLE_NAME.txt

    # # Load to psql
    sed -i 's/\r$//g' $TABLE_NAME.txt
    sed -i 's/\"//g' $TABLE_NAME.txt

    psql $RECIPE_ENGINE -c "CREATE SCHEMA IF NOT EXISTS $TABLE_NAME;"
    psql $RECIPE_ENGINE -c "DROP TABLE IF EXISTS $TABLE_NAME.\"$DATE\";"
    psql $RECIPE_ENGINE -c "CREATE TABLE $TABLE_NAME.\"$DATE\" ( BBL text, PARCELCARD text, BLDGNUM text, BLDGCLASS text, PRIMARYUSECODE text, DEVELOPMENTNAME text, STREETTYPE text, LOTTYPE text, RESIDAREA text, OFFICEAREA text, RETAILAREA text, GARAGEAREA text, STORAGEAREA text, FACTORYAREA text, OTHERAREA text, GROSSAREA text, OWNERAREA text, GROSSVOLUME text, COMMERCIALAREA text, PROXCODE text, BSMNT_TYPE text, BSMNTGRADIENT text, BSMNTAREA text, FIRSTFLOORAREA text, SECONDFLOORAREA text, UPPERFLOORAREA text, PARTRESFLOORAREA text, UNFINISHEDFLOORAREA text, FINISHEDFLOORAREA text, NONRESIDFLOORAREA text, RESIDCONSTRTYPE text, COMMERCIALCONSTRTYPE text, CONDOMAINCONSTRTYPE text, CONDOUNITSCONSTRTYPE text );"
    psql $RECIPE_ENGINE -c "\COPY $TABLE_NAME.\"$DATE\" FROM '`pwd`/$TABLE_NAME.txt' WITH NULL AS '' DELIMITER '|' CSV HEADER;"

    cd -; }

# Remove files
rm -r tmp
