name: Cook Runner

on: [push]

jobs:
  build:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: 
      image: sptkl/cook:latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      FTP_PREFIX: ${{ secrets.FTP_PREFIX }}
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .
    - name: run recipes ...
      run: |
        for recipe in ${{ github.event.head_commit.message }}
        do cook run $recipe
        done
