name: DOB pull for HED
on: [push]
jobs:
  migration:
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies ...
        run: |
          sudo apt update
          sudo apt install -y curl zip
          sudo apt autoremove
          
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
          
      - name: pull permits
        run: |
          DATE=$(date "+%Y-%m-%d")
          mc rm -r --force spaces/edm-storage/dob_permitissuance/latest
          mc rm -r --force spaces/edm-storage/dob_permitissuance/$DATE
          mkdir -p output
          curl https://data.cityofnewyork.us/api/views/ipu4-2q9a/rows.csv -o output/dob_permitissuance.csv
          mc cp output/dob_permitissuance.csv spaces/edm-storage/dob_permitissuance/latest/dob_permitissuance.csv
          mc cp output/dob_permitissuance.csv spaces/edm-storage/dob_permitissuance/$DATE/dob_permitissuance.csv
          rm output/dob_permitissuance.csv
      - name: pull applications
        run: |
          DATE=$(date "+%Y-%m-%d")
          mc rm -r --force spaces/edm-storage/dob_jobapplications/latest
          mc rm -r --force spaces/edm-storage/dob_jobapplications/$DATE
          mkdir -p output
          curl https://data.cityofnewyork.us/api/views/ic3t-wcy2/rows.csv -o output/dob_jobapplications.csv
          mc cp output/dob_jobapplications.csv spaces/edm-storage/dob_jobapplications/latest/dob_jobapplications.csv
          mc cp output/dob_jobapplications.csv spaces/edm-storage/dob_jobapplications/$DATE/dob_jobapplications.csv
          rm output/dob_jobapplications.csv
