name: Recipe Backup
on:
  schedule:
    - cron: '30 * * * *'
jobs:
  migration:
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: install dependencies ...
        run: |
          sudo apt update
          sudo apt install -y curl zip

          sudo tee /etc/apt/sources.list.d/pgdg.list <<END
          deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
          END

          # get the signing key and import it
          curl -O https://www.postgresql.org/media/keys/ACCC4CF8.asc
          sudo apt-key add ACCC4CF8.asc

          sudo apt update
          sudo apt install -y postgresql-client-11
          sudo apt autoremove
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
      - name: migrate meta.metadata
        run: |
          DATE=$(date "+%Y-%m-%d")
          mc rm -r --force spaces/edm-backup/recipes/latest
          mc rm -r --force spaces/edm-backup/recipes/$DATE
          psql $RECIPE_ENGINE -c "\copy (SELECT * FROM meta.metadata) TO stdout DELIMITER ',' CSV HEADER;" > recipes.csv
          mc cp recipes.csv edm-backup/recipes/latest/recipes.csv
          mc cp recipes.csv edm-backup/recipes/$DATE/recipes.csv
