name: Zoning Tax Lots Bulk Load

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    if: contains(github.event.issue.title, '[ztl]')
    runs-on: ubuntu-latest
    container: 
      image: nycplanning/cook:latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      FTP_PREFIX: ${{ secrets.FTP_PREFIX }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .
    - name: run recipes ...
      shell: bash
      run: |
        recipe_names=(
          'dcp_mih'
          'dcp_edesignation'
          'dcp_commercialoverlay'
          'dcp_limitedheight'
          'dcp_zoningdistricts'
          'dcp_specialpurpose'
          'dcp_specialpurposesubdistricts'
          'dcp_zoningtaxlots'
          'dcp_zoningmapamendments'
          'dof_dtm'
          'dof_shoreline'
          'dof_condo'
          'dcp_opendata_updates')
        # recipe_names includes files we get 
        # from GIS that are used for PLUTO updates too
        for recipe in ${recipe_names[*]}
        do cook run $recipe
        done
        
    - name: Comment on Issue
      if: success()
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          ## ${{ github.event.issue.title }} Is Successfully Updated! 🎉

          ### Source Info

          ${{ steps.report.outputs.report }}

          ### More Info
          for more details, check https://github.com/NYCPlanning/recipes/actions/runs/${{ github.run_id }}

        reactions: laugh, rocket, hooray
